apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "preview.fullname" . }}
  labels:
    {{- include "preview.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "preview.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "preview.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . | quote }}
      {{- end }}
      containers:
        - name: preview
          image: {{ .Values.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            - name: PREVIEW_COMMIT_SHA
              value: {{ .Values.commitSHA | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
