apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "preview.fullname" . }}
  labels:
    {{- include "preview.labels" . | nindent 4 }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "preview.fullname" . }}
                port:
                  name: http
